MAPPING_LANG_CODE_TO_TEXT = {
    "ar": "Arabic",
    "ca": "Catalan",
    "code": "code",
    "en": "English",
    "es": "Spanish",
    "eu": "Basque",
    "fr": "French",
    "id": "Indonesian",
    "indic-as": "Assamese",
    "indic-bn": "Bengali",
    "indic-gu": "Gujarati",
    "indic-hi": "Hindi",
    "indic-kn": "Kannada",
    "indic-ml": "Malayalam",
    "indic-mr": "Marathi",
    "indic-ne": "Nepali",
    "indic-or": "Odia",
    "indic-pa": "Punjabi",
    "indic-ta": "Tamil",
    "indic-te": "Telugu",
    "indic-ur": "Urdu",
    "nigercongo-ak": "Akan",
    "nigercongo-bm": "Bambara",
    "nigercongo-fon": "Fon",
    "nigercongo-ig": "Igbo",
    "nigercongo-ki": "Kikuyu",
    "nigercongo-lg": "Luganda",
    "nigercongo-ln": "Lingala",
    "nigercongo-nso": "Northern Sotho",
    "nigercongo-ny": "Chi Chewa",
    "nigercongo-rn": "Kirundi",
    "nigercongo-rw": "Kinyarwanda",
    "nigercongo-sn": "Chi Shona",
    "nigercongo-st": "Sesotho",
    "nigercongo-sw": "Swahili",
    "nigercongo-tn": "Setswana",
    "nigercongo-ts": "Xitsonga",
    "nigercongo-tum": "Chi Tumbuka",
    "nigercongo-tw": "Twi",
    "nigercongo-wo": "Wolof",
    "nigercongo-xh": "Xhosa",
    "nigercongo-yo": "Yoruba",
    "nigercongo-zu": "Isi Zulu",
    "pt": "Portuguese",
    "vi": "Vietnamese",
    "zhs": "Simplified Chinese",
    "zht": "Traditional Chinese",
}
